import type { Meal } from './types';

export const mealCategories = [
  'All',
  'Jollof Rice',
  'Swallow',
  'Snacks',
  'Drinks',
  'Soups',
];

export const allMeals: Meal[] = [
  {
    id: '1',
    name: 'Jollof Rice & Chicken',
    description: 'Classic Nigerian party jollof with a piece of spicy grilled chicken.',
    price: 2500,
    category: 'Jollof Rice',
    vendor: 'Mama Cass',
    imageId: 'jollof-rice',
  },
  {
    id: '2',
    name: 'Efo Riro & Pounded Yam',
    description: 'Rich vegetable soup with assorted meat, served with soft pounded yam.',
    price: 3500,
    category: 'Swallow',
    vendor: 'The Calabar Kitchen',
    imageId: 'efo-riro',
  },
  {
    id: '3',
    name: 'Fried Plantain (Dodo)',
    description: 'A sweet and savory side dish of ripe plantains, fried to perfection.',
    price: 500,
    category: 'Snacks',
    vendor: 'City Chefs',
    imageId: 'fried-plantain',
  },
  {
    id: '4',
    name: 'Spicy Meat Pie',
    description: 'Flaky pastry filled with seasoned minced meat. A perfect snack.',
    price: 700,
    category: 'Snacks',
    vendor: 'Mama Cass',
    imageId: 'meat-pie',
  },
  {
    id: '5',
    name: 'Chapman',
    description: 'A refreshing non-alcoholic cocktail, the perfect thirst quencher.',
    price: 1000,
    category: 'Drinks',
    vendor: 'The Calabar Kitchen',
    imageId: 'chapman',
  },
  {
    id: '6',
    name: 'Beef Suya',
    description: 'Grilled beef skewers coated in a spicy peanut blend.',
    price: 1500,
    category: 'Snacks',
    vendor: 'Suya Spot',
    imageId: 'suya',
  },
  {
    id: '7',
    name: 'Jollof Rice Special',
    description: 'Our signature jollof rice with plantain and a mix of beef and chicken.',
    price: 3200,
    category: 'Jollof Rice',
    vendor: 'City Chefs',
    imageId: 'jollof-rice',
  },
  {
    id: '8',
    name: 'Egusi Soup & Eba',
    description: 'Hearty melon seed soup with fish and meat, served with garri.',
    price: 3800,
    category: 'Soups',
    vendor: 'The Calabar Kitchen',
    imageId: 'egusi-soup',
  },
  {
    id: '9',
    name: 'Afang Soup & Fufu',
    description: 'A Calabar delicacy made with afang leaves and waterleaf.',
    price: 4500,
    category: 'Soups',
    vendor: 'The Calabar Kitchen',
    imageId: 'afang-soup',
  },
  {
    id: '10',
    name: 'Jollof Rice (Vendor Pack)',
    description: 'A large portion of jollof rice, perfect for sharing.',
    price: 2200,
    category: 'Jollof Rice',
    vendor: 'Suya Spot',
    imageId: 'jollof-rice',
  },
];
