
import type { Meal } from './types';

export const mealCategories = [
  'All',
  'Soups',
  'Specials',
  'Swallow',
  'Snacks',
  'Drinks',
];

export const allMeals: Meal[] = [
  {
    id: '1',
    name: 'Afang Soup & Swallow',
    description: 'A Calabar delicacy with afang leaves, waterleaf, and assorted meat/fish. Served with your choice of swallow.',
    price: 4500,
    category: 'Soups',
    vendor: 'The Calabar Kitchen',
    imageId: 'afang-soup',
    addons: [
      { id: 'extra-meat', name: 'Extra Beef', price: 500 },
      { id: 'extra-fish', name: 'Extra Fish', price: 700 },
      { id: 'extra-kpomo', name: 'Extra Kpomo', price: 300 },
    ],
  },
  {
    id: '2',
    name: 'Edikaikong Soup & Swallow',
    description: 'A rich, traditional Efik vegetable soup packed with assorted meats and seafood. Served with your choice of swallow.',
    price: 4800,
    category: 'Soups',
    vendor: 'Mama Cass',
    imageId: 'edikaikong-soup',
    addons: [
      { id: 'extra-meat', name: 'Extra Beef', price: 500 },
      { id: 'extra-stockfish', name: 'Extra Stockfish', price: 800 },
    ],
  },
  {
    id: '3',
    name: 'Afia Efere (White Soup)',
    description: 'A spicy, hearty white soup made without palm oil, featuring goat meat and local spices. Served with pounded yam.',
    price: 4200,
    category: 'Soups',
    vendor: 'City Chefs',
    imageId: 'afia-efere',
    addons: [
      { id: 'extra-goat-meat', name: 'Extra Goat Meat', price: 1000 },
    ],
  },
  {
    id: '4',
    name: 'Ekpang Nkukwo',
    description: 'A pottage of grated cocoyam and water yam, wrapped in tender leaves and cooked with periwinkles and seafood.',
    price: 3800,
    category: 'Specials',
    vendor: 'The Calabar Kitchen',
    imageId: 'ekpang-nkukwo',
  },
  {
    id: '5',
    name: 'Goat Meat Peppersoup',
    description: 'A spicy and aromatic broth with tender goat meat, a perfect comfort food.',
    price: 3000,
    category: 'Soups',
    vendor: 'Suya Spot',
    imageId: 'peppersoup',
  },
  {
    id: '6',
    name: 'Beef Suya',
    description: 'Grilled beef skewers coated in a spicy peanut blend, served with fresh onions and cabbage.',
    price: 1500,
    category: 'Snacks',
    vendor: 'Suya Spot',
    imageId: 'suya',
  },
  {
    id: '7',
    name: 'Atama Soup & Swallow',
    description: 'A flavorful palm fruit soup thickened with atama leaves, a true Akwa Ibom/Calabar classic.',
    price: 4600,
    category: 'Soups',
    vendor: 'City Chefs',
    imageId: 'atama-soup',
    addons: [
      { id: 'extra-meat', name: 'Extra Beef', price: 500 },
      { id: 'extra-fish', name: 'Extra Dry Fish', price: 700 },
    ],
  },
  {
    id: '8',
    name: 'Fisherman Soup',
    description: 'A rich seafood okra and vegetable soup, loaded with fresh fish, prawns, and crabs.',
    price: 5500,
    category: 'Soups',
    vendor: 'The Calabar Kitchen',
    imageId: 'fisherman-soup',
    addons: [
      { id: 'extra-prawns', name: 'Extra Prawns', price: 1200 },
      { id: 'extra-crab', name: 'Extra Crab', price: 1500 },
    ],
  },
  {
    id: '9',
    name: 'Pounded Yam',
    description: 'Soft, smooth, and stretchy dough, the perfect companion for your favorite soup.',
    price: 500,
    category: 'Swallow',
    vendor: 'The Calabar Kitchen',
    imageId: 'pounded-yam',
  },
  {
    id: '10',
    name: 'Garri (Eba)',
    description: 'A staple food made from cassava, prepared to be eaten with soups.',
    price: 300,
    category: 'Swallow',
    vendor: 'City Chefs',
    imageId: 'eba',
  },
  {
    id: '11',
    name: 'Jollof Rice & Chicken',
    description: 'Classic Nigerian party jollof with a piece of spicy grilled chicken.',
    price: 2500,
    category: 'Specials',
    vendor: 'Mama Cass',
    imageId: 'jollof-rice',
    addons: [
      { id: 'extra-chicken', name: 'Extra Chicken', price: 1000 },
      { id: 'plantain', name: 'Fried Plantain', price: 500 },
    ],
  },
  {
    id: '12',
    name: 'Chapman',
    description: 'A refreshing non-alcoholic cocktail, the perfect thirst quencher.',
    price: 1000,
    category: 'Drinks',
    vendor: 'The Calabar Kitchen',
    imageId: 'chapman',
  },
   {
    id: '13',
    name: 'Otong Soup',
    description: 'A delicious vegetable soup made with a blend of ugwu and uziza leaves.',
    price: 4300,
    category: 'Soups',
    vendor: 'City Chefs',
    imageId: 'otong-soup',
    addons: [
      { id: 'extra-meat', name: 'Extra Beef', price: 500 },
      { id: 'extra-fish', name: 'Extra Stockfish', price: 800 },
    ],
  },
  {
    id: '14',
    name: 'Abak Atama (Palm Nut Soup)',
    description: 'A flavorful soup made from palm fruit concentrate and atama leaves.',
    price: 4700,
    category: 'Soups',
    vendor: 'The Calabar Kitchen',
    imageId: 'abak-atama',
     addons: [
      { id: 'extra-meat', name: 'Extra Beef', price: 500 },
      { id: 'extra-fish', name: 'Extra Dry Fish', price: 700 },
    ],
  },
];
